### ISSUE TITLE
Error in bin centre computation for EMD

### ISSUE THREAD

**Issue by Hilly12** [synthesized-io/insight#35]
```python
bin_centers = bin_edges[:-1] + np.diff(bin_edges) / 2
```
This computation of bin centers is incorrect. Needs to be this.
```python
bin_centers = (bin_edges[:-1] + bin[1:]) / 2
```

Also if we want to handle the `bin_edges = None` case we could have something like this.
```python
def _compute_metric(self, x: pd.Series, y: pd.Series) -> float:
    (p, q), bin_edges = utils.zipped_hist((x, y), bin_edges=self.bin_edges, ret_bins=True)

    if bin_edges is None:
        bin_centers = np.arange(len(p))
    else:
        bin_centers = (np.array(bin_edges[:-1]) + np.array(bin_edges[1:])) / 2

    return wasserstein_distance(bin_centers, bin_centers, u_weights=p, v_weights=q)
```

If we change it to this there's no need to have a separate EMD (behaves the same as emd_samples from `pyemd`).

**Comment by akanksha1304** [comment]
I didn't get as to why should the bin centers be calculated as: (bin_edges[:-1] + bin[1:]) / 2 ; rather than as bin_edges[:-1] + np.diff(bin_edges) / 2

Suppose, bin_edges = [0, 5, 10, 15, 20]
then if, bin_centers = bin_edges[:-1] + np.diff(bin_edges) / 2
The above evaluates to: bin_centers = array([ 2.5,  7.5, 12.5, 17.5]) , which seems correct!

Please let me know why is it an issue?

**Comment by simonhkswan** [comment]
@akanksha1304  these look like the same calculation to me. Maybe it's not a bug.
